### ISSUE TITLE
Add new case study for Eminent IT on virtocommerce.com/case-studies

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#122]
Hello, would you please create a new case study box on virtocommerce.com/case-studies and a click-through page with the below content?

1) New case study box on this page: virtocommerce.com/case-studies
Logo: 
![eminent it-logo-white](https://user-images.githubusercontent.com/43222967/49704578-71244200-fbc9-11e8-938e-dafb5c881169.png)
Red category: GOVERNMENT SUPPLY CHAIN
TITLE: US Government Supply Chain Ecommerce Expedites Order Processing and Efficiency

2) Create new case study page for Eminent IT with this info:

![image](https://user-images.githubusercontent.com/43222967/49704665-9e252480-fbca-11e8-8088-1578c00f571f.png)

![image](https://user-images.githubusercontent.com/43222967/49704632-35d64300-fbca-11e8-9597-f2bc715449a4.png)
[Virto Commerce Case Study Eminent IT.pdf](https://github.com/VirtoCommerce/vc-content/files/2661151/Virto.Commerce.Case.Study.Eminent.IT.pdf)

**Comment by mpennie** [comment]
In the second sentence -- Can you please edit the word "consulting"? It is misspelled. Thank you.

**Comment by blazemachine** [comment]
Fixed.

**Comment by mpennie** [comment]
Hi Sergey: Will you please make it live?
@Sergey Podguzov<mailto:spo@virtoway.com>

Megan Pennie
Virto Commerce
https://virtocommerce.com
P: 323-377-1687 | Los Angeles, CA

[signature_1134461847]<https://www.virtocommerce.com/>

**Comment by mpennie** [comment]
Hi Sergey - I still do not see it live on virtocommerce.com/case-studies. Can you please check and make it live?
